# Face recognition classifier using CNN and TL(VGG16)

Face recognition is a multi class classification where we need to classify diff classes such as 'smille', 'theod', 'thgear', 'sjpalm', 'virvi', 'tjdyke', 'vanta', 'wjhugh', 'sjkill', 'theoc', 'sdwall', 'rjdunc', 'sirmcb', 'sjcutt', 'rhnorm', 'sgjday', 'sherbe', 'simm', 'sapere', 'riphil', 'pjrand', 'pcfry', 'pajaco', 'pears', 'papad', 'padnor', 'rhaitk', 'rafox', 'namart', 'ogefen', 'matth', 'ldgodd', 'llambr', 'mkosto', 'mrhami', 'mizli', 'kouri', 'lidov', 'labenm', 'mdchud', 'kmbald', 'ijfran', 'kbartl', 'isbald', 'hsgrim', 'howar', 'jross', 'jshea', 'jserai', 'jbierl', 'darda', 'dgemen', 'dakram', 'cywan', 'gsvird', 'gsmall', 'damvo', 'gstamo', 'hcarpe', 'dfhodd', 'ardper', 'cfloro', 'bschap', 'apdavi', 'boylee', 'cadugd', 'cdlarg', 'awjsud', 'apapou', 'cladam', 'adhast', 'ajbake'.

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/


#### Define the data path

In [0]:
import os
PATH = os.getcwd()
DATA_PATH = os.path.join(PATH, '/content/drive/My Drive/Data_InsofeNet/faces95')
data_dir_list = os.listdir(DATA_PATH)

In [0]:
# To avoid warnings from the tensorflow
import warnings
warnings.filterwarnings("ignore")

#### Get the list of folders inside data path

In [4]:
#printing data dir list
print(data_dir_list)

['smille', 'theod', 'thgear', 'sjpalm', 'virvi', 'tjdyke', 'vanta', 'wjhugh', 'sjkill', 'theoc', 'sdwall', 'rjdunc', 'sirmcb', 'sjcutt', 'rhnorm', 'sgjday', 'sherbe', 'simm', 'sapere', 'riphil', 'pjrand', 'pcfry', 'pajaco', 'pears', 'papad', 'padnor', 'rhaitk', 'rafox', 'namart', 'ogefen', 'matth', 'ldgodd', 'llambr', 'mkosto', 'mrhami', 'mizli', 'kouri', 'lidov', 'labenm', 'mdchud', 'kmbald', 'ijfran', 'kbartl', 'isbald', 'hsgrim', 'howar', 'jross', 'jshea', 'jserai', 'jbierl', 'darda', 'dgemen', 'dakram', 'cywan', 'gsvird', 'gsmall', 'damvo', 'gstamo', 'hcarpe', 'dfhodd', 'ardper', 'cfloro', 'bschap', 'apdavi', 'boylee', 'cadugd', 'cdlarg', 'awjsud', 'apapou', 'cladam', 'adhast', 'ajbake']


#### Declarations and initializations

In [0]:
img_rows=224
img_cols=224
num_channel=3

num_epoch=8
batch_size=32

img_data_list=[]
classes_names_list=[]

#### Read the images and store them in the list

In [6]:
import cv2

for dataset in data_dir_list:
    classes_names_list.append(dataset) 
    print ('Loading images from {} folder\n'.format(dataset)) 
    img_list=os.listdir(DATA_PATH+'/'+ dataset)
    for img in img_list:
        input_img=cv2.imread(DATA_PATH + '/'+ dataset + '/'+ img )
        input_img_resize=cv2.resize(input_img,(img_rows, img_cols))
        img_data_list.append(input_img_resize)

Loading images from smille folder

Loading images from theod folder

Loading images from thgear folder

Loading images from sjpalm folder

Loading images from virvi folder

Loading images from tjdyke folder

Loading images from vanta folder

Loading images from wjhugh folder

Loading images from sjkill folder

Loading images from theoc folder

Loading images from sdwall folder

Loading images from rjdunc folder

Loading images from sirmcb folder

Loading images from sjcutt folder

Loading images from rhnorm folder

Loading images from sgjday folder

Loading images from sherbe folder

Loading images from simm folder

Loading images from sapere folder

Loading images from riphil folder

Loading images from pjrand folder

Loading images from pcfry folder

Loading images from pajaco folder

Loading images from pears folder

Loading images from papad folder

Loading images from padnor folder

Loading images from rhaitk folder

Loading images from rafox folder

Loading images from namart fol

#### Get the number of classes

In [7]:
num_classes = len(classes_names_list)
print(num_classes)

72


####  Image preprocessiong

In [0]:
import numpy as np

img_data = np.array(img_data_list)
img_data = img_data.astype('float32')
img_data /= 255

In [9]:
print (img_data.shape)

(1440, 224, 224, 3)


In [10]:
class_mapping = {}

for index, directory in enumerate(os.listdir("/content/drive/My Drive/Data_InsofeNet/faces95")):
    class_mapping[index] = directory
print(class_mapping)

{0: 'smille', 1: 'theod', 2: 'thgear', 3: 'sjpalm', 4: 'virvi', 5: 'tjdyke', 6: 'vanta', 7: 'wjhugh', 8: 'sjkill', 9: 'theoc', 10: 'sdwall', 11: 'rjdunc', 12: 'sirmcb', 13: 'sjcutt', 14: 'rhnorm', 15: 'sgjday', 16: 'sherbe', 17: 'simm', 18: 'sapere', 19: 'riphil', 20: 'pjrand', 21: 'pcfry', 22: 'pajaco', 23: 'pears', 24: 'papad', 25: 'padnor', 26: 'rhaitk', 27: 'rafox', 28: 'namart', 29: 'ogefen', 30: 'matth', 31: 'ldgodd', 32: 'llambr', 33: 'mkosto', 34: 'mrhami', 35: 'mizli', 36: 'kouri', 37: 'lidov', 38: 'labenm', 39: 'mdchud', 40: 'kmbald', 41: 'ijfran', 42: 'kbartl', 43: 'isbald', 44: 'hsgrim', 45: 'howar', 46: 'jross', 47: 'jshea', 48: 'jserai', 49: 'jbierl', 50: 'darda', 51: 'dgemen', 52: 'dakram', 53: 'cywan', 54: 'gsvird', 55: 'gsmall', 56: 'damvo', 57: 'gstamo', 58: 'hcarpe', 59: 'dfhodd', 60: 'ardper', 61: 'cfloro', 62: 'bschap', 63: 'apdavi', 64: 'boylee', 65: 'cadugd', 66: 'cdlarg', 67: 'awjsud', 68: 'apapou', 69: 'cladam', 70: 'adhast', 71: 'ajbake'}


In [11]:
import matplotlib.pyplot as plt

image_arrays = []
image_labels = []

root_image_directory = "/content/drive/My Drive/Data_InsofeNet/faces95/"

for label, person in class_mapping.items():
    for directory in os.listdir(root_image_directory):
        if directory == person:
            image_directory = root_image_directory + directory
            break
 
    for image in os.listdir(image_directory):
        image = plt.imread(os.path.join(image_directory, image))
        image_arrays.append(image)
        image_labels.append(label)

image_arrays = np.array(image_arrays)
image_labels = np.array(image_labels)
print(image_arrays.shape, image_labels.shape)


(1440, 200, 180, 3) (1440,)


In [12]:
num_of_samples = img_data.shape[0]
input_shape = img_data[0].shape
print(num_of_samples)
print(input_shape)

1440
(224, 224, 3)


Convert class labels to numberic using one-hot encoding

In [13]:
from keras.utils import to_categorical

classes = to_categorical(image_labels, num_classes)

Using TensorFlow backend.


In [14]:
print(classes.shape)

(1440, 72)


#### Shuffle the dataset

In [0]:
from sklearn.utils import shuffle

X, Y = shuffle(img_data, classes, random_state=864)

In [16]:
print(X)

[[[[0.05882353 0.12156863 0.23529412]
   [0.05882353 0.12156863 0.23529412]
   [0.05882353 0.12156863 0.23529412]
   ...
   [0.0627451  0.1254902  0.23921569]
   [0.0627451  0.1254902  0.23921569]
   [0.0627451  0.1254902  0.23921569]]

  [[0.0627451  0.1254902  0.23921569]
   [0.0627451  0.1254902  0.23921569]
   [0.0627451  0.1254902  0.23921569]
   ...
   [0.06666667 0.12941177 0.24313726]
   [0.06666667 0.12941177 0.24313726]
   [0.06666667 0.12941177 0.24313726]]

  [[0.0627451  0.1254902  0.23921569]
   [0.0627451  0.1254902  0.23921569]
   [0.0627451  0.1254902  0.23921569]
   ...
   [0.06666667 0.12941177 0.24313726]
   [0.06666667 0.12941177 0.24313726]
   [0.06666667 0.12941177 0.24313726]]

  ...

  [[0.05882353 0.04705882 0.12941177]
   [0.05882353 0.04705882 0.12941177]
   [0.05490196 0.04705882 0.1254902 ]
   ...
   [0.03137255 0.03529412 0.07450981]
   [0.03137255 0.03529412 0.07450981]
   [0.03137255 0.03529412 0.07450981]]

  [[0.05490196 0.04705882 0.1254902 ]
   [0.0

#### Split the dataset

In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=456)
# Check the number of images in each dataset split
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

(1152, 224, 224, 3) (288, 224, 224, 3)
(1152, 72) (288, 72)


## CNN Model

In [0]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [0]:
###Defining the model
## Build the model
model = Sequential()

model.add(Conv2D(32, (3, 3),activation='relu', input_shape=input_shape))
model.add(Conv2D(32, (3, 3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))

model.add(Conv2D(64, (3, 3),activation='relu'))
model.add(Conv2D(64, (3, 3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

In [0]:
#Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])

In [22]:
#getting model summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 222, 222, 32)      896       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 220, 220, 32)      9248      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 110, 110, 32)      0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 110, 110, 32)      0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 108, 108, 64)      18496     
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 106, 106, 64)      36928     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 53, 53, 64)       

In [23]:
model.weights

[<tf.Variable 'conv2d_1/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
 array([[[[ 0.03837878,  0.06701146,  0.06052716,  0.09768201,
            0.11419468,  0.00716428,  0.0532514 ,  0.08306266,
           -0.07456577, -0.0628031 ,  0.06780033, -0.03465322,
           -0.06764877,  0.03440996, -0.05882552, -0.11859679,
            0.054405  ,  0.01485139, -0.03913885, -0.04261963,
            0.0069859 ,  0.07725108, -0.13569713,  0.1228034 ,
           -0.05619332,  0.11223073, -0.10645942,  0.00122264,
           -0.08916814, -0.06103778, -0.07287693,  0.05063576],
          [ 0.10715899,  0.00951467, -0.01578819,  0.09564355,
            0.08058687, -0.06561873, -0.07845733, -0.0765424 ,
           -0.06753031, -0.02556295,  0.09655604,  0.00508502,
            0.11358215,  0.12461112, -0.06070097, -0.10835689,
            0.12109847,  0.13700022, -0.05250804, -0.04472808,
            0.10158128, -0.08719398, -0.04198384, -0.00642067,
           -0.11277898,  0.09310658,  0.0

In [24]:
model.layers

#### Training the model 

In [25]:
%%time
hist = model.fit(X_train, y_train, batch_size=batch_size, epochs=num_epoch, verbose=1, validation_data=(X_test, y_test))

Train on 1152 samples, validate on 288 samples
Epoch 1/8
1152/1152 [==============================] - 270s 235ms/step - loss: 4.2054 - accuracy: 0.0417 - val_loss: 3.7859 - val_accuracy: 0.1285
Epoch 2/8
1152/1152 [==============================] - 264s 229ms/step - loss: 3.2523 - accuracy: 0.1806 - val_loss: 2.6550 - val_accuracy: 0.3472
Epoch 3/8
1152/1152 [==============================] - 254s 221ms/step - loss: 2.3105 - accuracy: 0.4080 - val_loss: 1.9256 - val_accuracy: 0.5382
Epoch 4/8
1152/1152 [==============================] - 257s 223ms/step - loss: 1.5710 - accuracy: 0.5703 - val_loss: 1.2168 - val_accuracy: 0.7118
Epoch 5/8
1152/1152 [==============================] - 255s 221ms/step - loss: 1.0621 - accuracy: 0.7031 - val_loss: 0.8987 - val_accuracy: 0.7951
Epoch 6/8
1152/1152 [==============================] - 265s 230ms/step - loss: 0.9112 - accuracy: 0.7300 - val_loss: 0.8068 - val_accuracy: 0.8021
Epoch 7/8
1152/1152 [==============================] - 265s 230ms/step 

In [26]:
#Evaluating the model
score = model.evaluate(X_test, y_test, batch_size=batch_size)

print('Test Loss:', score[0])
print('Test Accuracy:', score[1])

288/288 [==============================] - 14s 49ms/step
Test Loss: 0.6490501827663846
Test Accuracy: 0.8333333134651184


In [0]:
#predicting on test data
from sklearn.metrics import confusion_matrix

Y_pred = model.predict(X_test)

In [28]:
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)

[68 69 35  0 44 14 60 67 24 46 68 13 70 44 58  4 66  5 39 21 30 67 62 58
  2 24  3 13 69 46 28 30 19  9 26 71 49 26  2 62 24 24 40 29 64 26  7 52
  4  2 14 18 67  0  9 17  7  4 60 41 33 26 23  9  3 26 69 49 13 67 41 25
 71 34 46 28 40  7 23 57 49 25 29 28 58  8 31 56 28 30 27 29 47 35 53 68
 36 67 59 40 52 39 38 18  0 48 32 30 29 41 42 13 23  3 23 70 26  1 50 66
 19 13  8 23 42 51 46 70 43 26 41  0 67 66 13 35 69 15 52 37 58 44 43 54
 21 16  0  8 51 29 18 35  2 48 62 67 45 68 34 17 50 19 24 41 22 61 60 49
 33 29  4 10 68 26 37 17 64 44  0 54  0 63 31  6 23 15 44 59 45 29 57 48
 15 16 71 27 10 38 33 10 18  6 43 15 21 27 18 44 11 24 68 31 45 50 15 17
 53  6  1 25  4 35 20  1 27 43 40 59  2 34  4 60 14 53 25 31 62 17 29 17
 53  0 67 64 15 46  7 36 43 45 59 38 10 65 26 66 26 32 61 29 54 10 18 32
 49 63  8 16 65 32 42 31 71 29 21 50 57 61 36 57 26 32 16 11 57  9 16 14]


In [29]:
#compute the confusion matrix
print(confusion_matrix(np.argmax(y_test, axis=1), y_pred))

[[5 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 5 ... 0 0 0]
 ...
 [0 0 0 ... 4 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 4]]


#### Saving and loading model and weights

In [0]:
from keras.models import model_from_json, load_model

In [0]:

# Serialize weights to HDF5
model.save_weights("modelcnn.h5")
model.save("modelcnn.hdf5")

In [0]:
# Load weights into new model
model.load_weights("modelcnn.h5")
loaded_model = load_model('modelcnn.hdf5')

# Transfer Learning (VGG16)

In [0]:
from keras.layers import Input, Dense

In [0]:
# Custom_vgg_model
#Training the classifier alone
image_input = Input(shape=(img_rows, img_cols, num_channel))

In [0]:
from keras.applications.vgg16 import VGG16

model_vgg = VGG16(input_tensor=image_input, include_top=True, weights='imagenet')

In [37]:
model_vgg.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [0]:
last_layer = model_vgg.get_layer('fc2').output
out = Dense(num_classes, activation='softmax', name='output')(last_layer)

In [39]:
from keras.models import Model

custom_vgg_model = Model(image_input, out)
custom_vgg_model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0   

In [0]:
for layer in custom_vgg_model.layers[:-1]:
    layer.trainable = False

In [0]:
custom_vgg_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [42]:
%%time
custom_vgg_model.fit(X_train, y_train, batch_size=batch_size, epochs=num_epoch, verbose=1, validation_data=(X_test, y_test))

Train on 1152 samples, validate on 288 samples
Epoch 1/8
1152/1152 [==============================] - 719s 624ms/step - loss: 4.9985 - accuracy: 0.0286 - val_loss: 4.2164 - val_accuracy: 0.0486
Epoch 2/8
1152/1152 [==============================] - 718s 623ms/step - loss: 3.9453 - accuracy: 0.1502 - val_loss: 3.6126 - val_accuracy: 0.2431
Epoch 3/8
1152/1152 [==============================] - 719s 624ms/step - loss: 3.3452 - accuracy: 0.2708 - val_loss: 3.1812 - val_accuracy: 0.3160
Epoch 4/8
1152/1152 [==============================] - 721s 626ms/step - loss: 2.9018 - accuracy: 0.3845 - val_loss: 2.6669 - val_accuracy: 0.4514
Epoch 5/8
1152/1152 [==============================] - 733s 636ms/step - loss: 2.5066 - accuracy: 0.4549 - val_loss: 2.5722 - val_accuracy: 0.4688
Epoch 6/8
1152/1152 [==============================] - 719s 624ms/step - loss: 2.2349 - accuracy: 0.5312 - val_loss: 2.3202 - val_accuracy: 0.5208
Epoch 7/8
1152/1152 [==============================] - 719s 624ms/step 

In [43]:
(loss, accuracy) = custom_vgg_model.evaluate(X_test, y_test, batch_size=batch_size, verbose=1)

print("[INFO] loss={:.4f}, accuracy: {:.4f}%".format(loss, accuracy * 100))

288/288 [==============================] - 145s 502ms/step
[INFO] loss=1.5497, accuracy: 74.6528%


In [0]:
Y_train_pred = custom_vgg_model.predict(X_test)

In [45]:
y_train_pred = np.argmax(Y_train_pred, axis=1)
print(y_train_pred)

[68 69 35  0 64 15 60 67 24 46 33 13 69 44 58  4 56  5 39 21 30 16 62 33
  2 24 20 13 69 46 56 64 19  9 68 71 49 26  2 62 24 24 40 55 64 43 56 52
  4  2 71 10 16  0  9 47 47  4 60 41 33 26 56  9 33 26 69 49 13 51 69 25
 71 32 46 56 40 33 23  6 49 25 47 30 33 39 31 56 56 30 27 55 47 35 53 68
 36 30 32 40 52 47 38 68 43 47 32 30 55 41 42 13 23 33 23 47 26  1 50 66
 33 13  8 23 22 51 46 32 43 26 41  0 64 66 44 35 69 15 52 42 33 44 43 54
 21 16  6  6 23 55 33 35  2 47 27 30 45 68 34 17 50 33 24  1 22 26 60 49
 33 26  4 10 68 26 42 29 64 44  0 54  0 69 31  6 23 15 44 33 45 55  6 47
 15 16 71 27 10 38 33 71 49  6 43 15 21 27 33 47  2 30 68 31 45 50 15 20
 33 68 30 25  4 35 20  1 27 43 40 30  2 32  4 33 60 53 25 31 62 31 64 68
 51 17 30 64 15 46 36 36 47 45 13 38 10 65 26 66 26 32 47 55  1 10  6 32
 49 63  8 16 65 32 42 31 71 47 21 50  6 47 36  6 26 32 16 47  6  9 30 56]


In [46]:
print(confusion_matrix(np.argmax(y_test, axis=1), y_train_pred))

[[5 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 6 ... 0 0 0]
 ...
 [0 0 0 ... 4 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 5]]


**Conclusion**:
The final accuracy is much higher than 50% baseline . However, it could be increased by larger number of train images or through model hyperparameters tuning.